<a href="https://colab.research.google.com/github/RajAakash/Transformers/blob/main/EmbeddingExample.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
import torch
import torch.nn as nn
from scipy.sparse import csr_matrix

# Create a sparse matrix X_train
X_train = csr_matrix(np.array([[1, 0, 1, 0],
                               [0, 0, 1, 1],
                               [1, 1, 1, 0]]))

print(f'here is X_train {X_train}')

# Get the first row of the sparse matrix
row = X_train.getrow(0)

print(f'row-{row}-row here')

# Create a linear layer with input size 4 and output size 3 (bias is set to False)
w_linear = nn.Linear(4, 3, bias=False)

# Print the weight of the linear layer
print(w_linear.weight)

# Print the output of the linear layer when applied to the first row of the sparse matrix
print(w_linear(torch.FloatTensor(row.toarray())))

# Create an embedding layer with input size 4 and output size 3, initialize with the weights from the linear layer
w_embedding = nn.Embedding(4, 3).from_pretrained(w_linear.weight.T)

# Print the weight of the embedding layer
print(w_embedding.weight)

# Print the output of the embedding layer when applied to the sum of indices of the first row
print(w_embedding(torch.tensor(row.indices).sum(0)))

here is X_train   (0, 0)	1
  (0, 2)	1
  (1, 2)	1
  (1, 3)	1
  (2, 0)	1
  (2, 1)	1
  (2, 2)	1
row-  (0, 0)	1
  (0, 2)	1-row here
Parameter containing:
tensor([[ 0.3552,  0.3508,  0.4610, -0.4364],
        [ 0.4581,  0.0826,  0.0405,  0.2970],
        [-0.1293,  0.2985,  0.1227, -0.3119]], requires_grad=True)
tensor([[ 0.8162,  0.4986, -0.0067]], grad_fn=<MmBackward0>)
Parameter containing:
tensor([[ 0.3552,  0.4581, -0.1293],
        [ 0.3508,  0.0826,  0.2985],
        [ 0.4610,  0.0405,  0.1227],
        [-0.4364,  0.2970, -0.3119]])
tensor([0.4610, 0.0405, 0.1227])


In [13]:
import torch
import torch.nn as nn

# Define an embedding layer with vocabulary size 100 and embedding dimension 32
embedding_layer = nn.Embedding(100, 32)

# Input tensor with integer indices
input_indices = torch.tensor([1, 5, 20, 3])

# Apply the embedding layer
output = embedding_layer(input_indices)

print(output.shape)  # Output shape: torch.Size([4, 32]) - 4 rows (input indices), each with a 32-dimensional embedding

torch.Size([4, 32])


In [14]:
import torch
import torch.nn as nn

# Define a linear layer with input size 10 and output size 5
linear_layer = nn.Linear(10, 5)

# Input tensor with size (batch_size, input_size)
input_data = torch.rand(32, 10)

# Apply the linear layer
output = linear_layer(input_data)

print(output.shape)  # Output shape: torch.Size([32, 5]) - 32 rows (batch size), each with 5 output values


torch.Size([32, 5])
